### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by PandaOnChain** [ryu666zaki/OKX-Withdrawal#1]
делаю по инструкции, но получаю ошибку: Withdraw error
okx {"code":"58350","data":[],"msg":"Insufficient balance"}

скрипт верно определяет баланс, но при попытке вывести ошибка.

**Comment by PandaOnChain** [comment]
комиссия будет уходить с основного, а выводиться будет с торгового. 
поэтому нужно, чтобы на обоих счетах был баланс.

**Comment by ryu666zaki** [comment]
> комиссия будет уходить с основного, а выводиться будет с торгового.
> поэтому нужно, чтобы на обоих счетах был баланс.

Переделал код. обновись и сделай все по новому гайду
