### ISSUE TITLE
Withdraw error. 'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by kp6c6p6c** [ryu666zaki/OKX-Withdrawal#2]
Похоже не подтягивается какая то переменная при выводе. 
.....
Available networks for USDC: OKTC, ERC20, TRC20, Polygon, Avalanche C, Arbitrum one, Optimism
Choose network: Arbitrum one
Enter addresses and amounts (e.g wallet1:amount1,wallet2:amount2, ...): 0x91e5.......249A2:10
Min delay (seconds): 10
Max delay (seconds): 10
Withdraw 10.0 USDC to wallet 0x91e5.......249A2
Withdraw error
'NoneType' object has no attribute 'upper'

**Comment by kp6c6p6c** [comment]
Типа фикс.. 

result = exchange.withdraw(symbol, amount, wallet, params={'toAddress': wallet, _**'network':'Arbitrum one'**,_ 'chainName': 'USDC-Arbitrum one', 'dest': 4, 'fee': network_fee, 'pwd': '-', 'amt': str(amount)})

**Comment by ryu666zaki** [comment]
> Типа фикс..
> 
> result = exchange.withdraw(symbol, amount, wallet, params={'toAddress': wallet, _**'network':'Arbitrum one'**,_ 'chainName': 'USDC-Arbitrum one', 'dest': 4, 'fee': network_fee, 'pwd': '-', 'amt': str(amount)})

переписал код, обнови репозиторий и следуй новой инструкции.
